### ISSUE TITLE
스켈레톤 작성

### ISSUE THREAD

**Issue by Seodj** [Seodj/calculator#1]
main() 함수

**Comment by karl-park** [comment]
스켈레톤 작성 언어는 뭘로 하나요?

**Comment by karl-park** [comment]
두둠칫 
⊂_ヽ
　 ＼＼ Λ＿Λ 
　　 ＼( ‘ㅅ' ) 두둠칫
　　　 >　⌒ヽ
　　　/ 　 へ＼
　　 /　　/　＼＼ 
　　 ﾚ　ノ　　 ヽ_つ
　　/　/두둠칫
　 /　/|
　(　(ヽ
　|　|、＼
　| 丿 ＼ ⌒)
　| |　　) /
`ノ )　　Lﾉ

**Comment by Seodj** [comment]
@MrKarl 두둠치 두둠칫

**Comment by MJ-Youn** [comment]
@MrKarl  @Seodj  @ssucom502

**Comment by karl-park** [comment]
@Seodj 나랏말쌈이 듕국에
